### ISSUE TITLE
Add Swift Package Manager Support

### ISSUE THREAD

**Issue by yoojinsca** [PhenixRTS/iOSSDK#17]
Many modern iOS/tvOS systems use Swift Package Manager.

It would be great to add this support.

**Comment by martres** [comment]
Any update on this ?

**Comment by tgronk** [comment]
Support for SPM can be found here. 

[https://github.com/PhenixRTS/swift-phenixrtssdk](https://github.com/PhenixRTS/swift-phenixrtssdk)
